### PR TITLE
rewrite with cobra

### PR DESCRIPTION
**Pull request by abs3ntdev**
replaced getopt library with cobra. allows for tab completions and better flag parsing. and better framework for subcommand in the future (convert). added new makefile, edited goreleaser config file(should test that or rewrite it if you don't like)

if you or someone could test with --ctl that would be cool i don't have hyprland installed atm

### CODE REVIEW

**Comment by NotAShelf** [comment]
I'll do some testing later today.

**Comment by NotAShelf** [comment]
Sorry it took me too long to test.

Currently it looks like the flag system is working pretty good.

[Sample output](https://p.frzn.dev/1tr/) for `go run . -btmv` (--binds, --from-ctl, --markdown, --variables)

**Comment by NotAShelf** [comment]
@abs3ntdev unless if you have objections, I'll simply merge this - it looks good enough to me and if there are problems I can probably patch those real quick, now that I'm on my main machine

**Comment by abs3ntdev** [comment]
Seems fine 2 me

**Pull request merged**
